"""Pesan perubahan atau migrasi yang dilakukan

Revision ID: cff69dac3953
Revises: 
Create Date: 2024-09-10 07:43:45.787740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cff69dac3953'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('activity_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.alter_column('age_group',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('nannies_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.alter_column('nanny_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('activity_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('nanny', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('sex',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('availability',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nanny', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('availability',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('sex',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('nannies_activities', schema=None) as batch_op:
        batch_op.alter_column('activity_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('nanny_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('date')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('age_group',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('activity_name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
