name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Ubah jika branch utama berbeda
  pull_request:
    branches:
      - main # Ubah jika branch utama berbeda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Update to the latest version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Update to the latest version

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Tambahkan Docker Hub username di Secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Tambahkan Docker Hub password di Secrets

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Pastikan ini adalah lokasi yang tepat dari source code kamu
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nannies-project:latest # Ganti dengan Docker Hub username dan nama image

  deploy:
    runs-on: ubuntu-latest
    needs: build # Pastikan deploy dijalankan setelah build selesai

    steps:
      - name: Deploy to server via SSH with password
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/nannies-project:latest
            docker stop nannies-project || true
            docker rm nannies-project || true
            docker run -d --network="host" --name nannies-project ${{ secrets.DOCKER_USERNAME }}/nannies-project:latest

      - name: Wait for container to be healthy
        run: |
          for i in {1..10}; do
            if docker inspect --format '{{.State.Health.Status}}' nannies-project | grep -q "healthy"; then
              echo "Container is healthy"
              exit 0
            else
              echo "Waiting for container to be healthy..."
              sleep 10
            fi
          done
          echo "Container failed to become healthy"
          exit 1
